{
  "formatVersion": "1.1",
  "component": {
    "group": "com.easydesq",
    "module": "ed-commons",
    "version": "1.0.8.feature.contractbillingbharat.snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-plain.jar",
          "url": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-plain.jar",
          "size": 100353,
          "sha512": "b8339d88a226c623d3699e53e270d000f56e8c0b1b5b972bd8e803677de7014cc851f391879b6a1e4cb58f251442093a7806a877519aff28d859b916d96dadbd",
          "sha256": "a8d4d8ea7b8e43863cef0a958038e9cd50240f8cf280b8eca1e9d22eb4835516",
          "sha1": "409ba08850b68d2b1095f48ba5884354441f8cf4",
          "md5": "21b99e027021cc176c7b69342d32a4a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.24"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java"
        }
      ],
      "files": [
        {
          "name": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-plain.jar",
          "url": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-plain.jar",
          "size": 100353,
          "sha512": "b8339d88a226c623d3699e53e270d000f56e8c0b1b5b972bd8e803677de7014cc851f391879b6a1e4cb58f251442093a7806a877519aff28d859b916d96dadbd",
          "sha256": "a8d4d8ea7b8e43863cef0a958038e9cd50240f8cf280b8eca1e9d22eb4835516",
          "sha1": "409ba08850b68d2b1095f48ba5884354441f8cf4",
          "md5": "21b99e027021cc176c7b69342d32a4a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-sources.jar",
          "url": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-sources.jar",
          "size": 47129,
          "sha512": "d1ea5f58dbb3a3716906e6a60177e34a5a2f80c64c46bade519dfa22b41cf0796459e2fcf4e20051e09dc4d068c3cd710d8eb3c960124173b53ab6fff1494b7a",
          "sha256": "336d0660145d5ba4a9935683aec22a539dd7a04e93e2c3a0c415c6910b59743b",
          "sha1": "411400c86944103a02f6122e99c3f6105075fcb9",
          "md5": "5727ffd6866d053400797c34272d145b"
        }
      ]
    }
  ]
}
