{
  "formatVersion": "1.1",
  "component": {
    "group": "com.easydesq",
    "module": "ed-commons",
    "version": "1.0.8.feature.contractbillingbharat.snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-plain.jar",
          "url": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-plain.jar",
          "size": 100897,
          "sha512": "32b1769fe577c281e94d4c9dff418d7b20b1eb8628abbdc31ffc66cc697e15317f78cabc5f42963d3feb8274b52d76e4c3d52cb76a60ff5eca27ad79cd8029e1",
          "sha256": "64663cdb41cf597762e19d81621909dd070c1a5f758fc2abdac611d0299687be",
          "sha1": "9a7cfdd26d7cb71810e2abfc114fc83ecf79b4ec",
          "md5": "aa4c25dab31d310a28daa85a946135a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.24"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java"
        }
      ],
      "files": [
        {
          "name": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-plain.jar",
          "url": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-plain.jar",
          "size": 100897,
          "sha512": "32b1769fe577c281e94d4c9dff418d7b20b1eb8628abbdc31ffc66cc697e15317f78cabc5f42963d3feb8274b52d76e4c3d52cb76a60ff5eca27ad79cd8029e1",
          "sha256": "64663cdb41cf597762e19d81621909dd070c1a5f758fc2abdac611d0299687be",
          "sha1": "9a7cfdd26d7cb71810e2abfc114fc83ecf79b4ec",
          "md5": "aa4c25dab31d310a28daa85a946135a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-sources.jar",
          "url": "ed-commons-1.0.8.feature.contractbillingbharat.snapshot-sources.jar",
          "size": 47542,
          "sha512": "a5f9e61645e65913daa25c0e9c6fc338fd93c6ac314eba61a2907087c1abbf4d576c0694c6613faf6cb4f84f45210adfeadd4024e4074a0816499ed6cf46d1e0",
          "sha256": "f98c2883066d74442d78955bb77a20662c791ccad74a69efbd9d19c15a4a1daa",
          "sha1": "b1028c7883c1b61963ef77c28053800efda14db5",
          "md5": "9b5a303e8b3ce4766e1fa0fe22b1cc6f"
        }
      ]
    }
  ]
}
